# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.7
exclude: /migrations/|/node_modules/|/venv/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
#    - id: check-added-large-files
#    - id: check-merge-conflict
    - id: check-symlinks
    - id: debug-statements
      exclude: _pytest/debugging.py
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
      args: [ --remove ]
    - id: name-tests-test
      args: [ --django ]
      exclude: ^(apps/fcldinfra/tests/settings/|apps/portal/src/extender/tests/expected_tests_api/)
    - id: trailing-whitespace
#-   repo: https://github.com/psf/black
#    rev: 19.3b0
#    hooks:
#    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      args: ['--config=setup.cfg', '--max-line-length=99']
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
