FROM python:3.7-alpine
RUN apk update && apk upgrade && apk add bash
ADD requirements/requirements.txt requirements/requirements-tests.txt /tmp/
RUN pip install -r /tmp/requirements.txt -r /tmp/requirements-tests.txt
WORKDIR /code
ADD backend /code
RUN mkdir -p /code/frontend/build
RUN touch /code/frontend/build/index.html
RUN python manage.py collectstatic --noinput -c
RUN chmod +x entrypoint.sh
ENTRYPOINT ["sh",  "entrypoint.sh"]
