version: "3.0"
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    command: tests
  quality:
    build:
      context: .
      dockerfile: Dockerfile-quality
    command: quality
