version: "2.1"
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    command: tests
    volumes:
      - ${TEST_VOLUME-./test-reports/}:/test-reports/
      - ${COVERAGE_VOLUME-./coverage-reports/}:/coverage-reports/
  quality:
    build:
      context: .
      dockerfile: Dockerfile-quality
    command: quality
