FROM python:3.7-alpine
RUN apk update && apk upgrade && apk add git
RUN pip install pre-commit
WORKDIR /code
ADD .pre-commit-config.yaml .pre-commit-config.yaml
RUN git init . && pre-commit install-hooks --config .pre-commit-config.yaml
ADD backend /code
RUN git stage -f ./*
RUN chmod +x entrypoint.sh
ENTRYPOINT ["sh",  "entrypoint.sh"]
